export function getPlaceholder(): string {
  const strings = [
    "Sol Ring...",
    "Mox Diamond...",
    "Urza, Lord High Artificier...",
    "Farewell...",
    "Lightning Bolt...",
    "Counterspell...",
    "Wrath of God...",
    "Black Lotus...",
    "Time Walk...",
    "Demonic Tutor...",
    "Ancestral Recall...",
    "Tarmogoyf...",
    "Snapcaster Mage...",
    "Thoughtseize...",
    "Lightning Helix...",
    "Swords to Plowshares...",
    "Doom Blade...",
    "Path to Exile...",
    "Dreadbore...",
    "Terminate...",
    "Liliana of the Veil...",
    "Jace, the Mind Sculptor...",
    "Cataclysm...",
    "Damnation...",
    "Dread Return...",
    "Grave Titan...",
    "Inferno Titan...",
    "Darksteel Colossus...",
    "Steel Hellkite...",
    "Emrakul, the Aeons Torn...",
    "Griselbrand...",
    "Blightsteel Colossus...",
    "Kozilek, Butcher of Truth...",
  ];
  return strings[Math.floor(Math.random() * strings.length)];
}
